spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;NON_KEYWORDS=USER

  redis:
    host: localhost
    port: 6379
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: bookyouseat22@gmail.com
    password: mjcfwlmsvdoytzhz
    properties:
      mail:
        smtp:
          auth: true
          timeout: 6000
          starttls:
            enable: true

jwt:
  secret: secretsecretsecretkeykeykeykeykeykey
  login_expiration_time: 7200 #2시간
  queue_expiration_time: 3600 # 1시간

mail:
  expiration_time: 300 #5분